### ISSUE TITLE
UmsApplication跑不了

### ISSUE THREAD

**Issue by Professor-mai** [mtcarpenter/mall-cloud-alibaba#7]
![image](https://user-images.githubusercontent.com/58881904/97882515-a9554080-1d5e-11eb-832d-8f01d1b98a7b.png)

**Comment by mtcarpenter** [comment]
你需要 把 docs 的配置文件上传到nacos 服务端

**Comment by Professor-mai** [comment]
我把开发环境都改成了dev，用本地的yml文件也要上传吗

**Comment by mtcarpenter** [comment]
> 我把开发环境都改成了dev，用本地的yml文件也要上传吗

不需要 但是里面的配置需要复制进来
